apiVersion: v1
data:
  datasource.yml: "apiVersion: 1\n\ndatasources:\n- name: Prometheus\n  type: prometheus\n  url: http://prometheus:9090 \n  isDefault: true\n  access: proxy\n  editable: true\n"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana-cm0
