apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: grafana-secrets
                      key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                  secretKeyRef:
                      name: grafana-secrets
                      key: GF_SECURITY_ADMIN_USER
          image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: grafana-cm0
          name: grafana-cm0
