# This is done in educational purpose only. I would never expose secrets in repo :)

apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
type: Opaque
data:
    GF_SECURITY_ADMIN_USER: YWRtaW4=  
    GF_SECURITY_ADMIN_PASSWORD: Z3JhZmFuYQ==
